README.md

reademe update 이제진짜끝

---

src/main/java/gwasuwonshot/tutice/external/firebase/service/FCMService.java

---
closes #12 
<br/>
---
- 파베 플젝 생성
- json 파일변경(gitignore)
- FCMService 변경
<br/>
---

[fix] updateFirebaseConfig

---

README.md

FCMService 변경사항 배포

---

src/main/java/gwasuwonshot/tutice/common/advice/ControllerExceptionAdvice.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
src/main/java/gwasuwonshot/tutice/external/firebase/service/FCMService.java
src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestAccount.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestRegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonByUserResponseDto.java
src/main/java/gwasuwonshot/tutice/lesson/repository/LessonRepository.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
closes #20 
<br/>
---
- 유저아이디로 유저 롤을 찾아서 연결된 수업을 가져옴
<br/>
---

[feat] get lesson by user

---

src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestRegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java

---
closes #25 
<br/>
---
- enum validation을 createLessonRequestDto에 적용
-
<br/>
---

[fix] updateEnumValidation to CreateLessonRequestDto

---

src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
src/main/java/gwasuwonshot/tutice/user/dto/request/LocalLoginRequestDto.java
src/main/java/gwasuwonshot/tutice/user/exception/authException/InvalidPasswordException.java
src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
closes #23 
<br/>
---
- 이메일 및 provider를 통해 존재하는 'LOCAL' 유저인지 확인
- 비밀번호 암호화된 값과 요청받은 비밀번호와 비교해 일치 여부 확인
- 성공 시, 토큰 및 이름과 role 전달
<br/>
---

[feat] localLogin

---

src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/common/resolver/userIdx/UserIdxResolver.java
src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
src/main/java/gwasuwonshot/tutice/user/dto/request/UpdateUserDeviceTokenRequestDto.java
src/main/java/gwasuwonshot/tutice/user/entity/User.java
src/main/java/gwasuwonshot/tutice/user/exception/authException/NullAccessTokenException.java
src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
closes #33 
<br/>
---
- deviceToken에 대한 setter를 만들어서 디바이스 토큰 업데이트
<br/>
---
- NullAccessTokenException 생성했습니당당

[feat] updateUserDeviceToken

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByParentsResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
src/main/java/gwasuwonshot/tutice/user/entity/User.java

---
closes #36
<br/>
---
- 유저 존재 여부 확인
- 유저가 '부모님'인지 확인
- 오늘의 수업 유무 체크 후, 그에 따른 response 반환
<br/>
---
부모님 수업 리스트 양방향 매핑으로 수정하기 !

[feat] getTodayScheduleByParents

---

src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/LessonAssembler.java
src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/PaymentRecordAssembler.java
src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/RegularScheduleAssembler.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
src/main/java/gwasuwonshot/tutice/lesson/entity/PaymentRecord.java
src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/schedule/dto/assembler/ScheduleAssembler.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByParentsResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #42
<br/>
---
- 
-
<br/>
---

[fix] date->localDate, time->localTime 타입 변경

---

src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/EnumValidator.java
src/main/java/gwasuwonshot/tutice/external/firebase/service/FCMService.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/schedule/dto/assembler/ScheduleAssembler.java
src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java

---
closes #18
<br/>
---
- Schedule 도메인과 RegularSchedule 도메인에서 스케쥴 자동생성 함수 생성
- RegularSchedule도메인에서 시작날짜와 가장 가까운 다가오는 요일을 기준으로 재정렬 
- 재정렬된 RegularSchedule과 회차를 기준으로 스케쥴 생성
- lessonService의 createLesson 로직에 스케쥴 자동생성 추가 
<br/>
---

[fix] crateAutoSchedule & update craete lesson

---

src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/LessonAssembler.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestAccount.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestDto.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestRegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/UpdateLessonParentsRequestDto.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
src/main/java/gwasuwonshot/tutice/lesson/exception/AlreadyExistLessonParentsException.java
src/main/java/gwasuwonshot/tutice/lesson/exception/InvalidLessonCodeException.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
closes #38 
<br/>
---
- 유저 역할검수
- 레슨코드 해독
- 레슨에 연결된 부모님 user 개체 검수
<br/>
---
레슨에 이미 부모님이 연결되어있더라도 해당 부모님 유저가 현재유저이면 성공임

[feat]update lesson parents

---

src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonMaintenanceRequestDto.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
src/main/java/gwasuwonshot/tutice/lesson/exception/AlreadyFinishedLessonException.java
src/main/java/gwasuwonshot/tutice/lesson/exception/InvalidLessonException.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java

---
closes #48 
<br/>
---
- 연장로직이 들어오면 가장 최근 스케쥴의 날짜 +1 을 하고 자동 스케쥴 생성로직 돌리기
- 연장안하면 isFinished true로 변경
<br/>
---

[feat] create lesson maintenance

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByTeacherResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodaySchedule.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayScheduleByTeacher.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayScheduleDetailByTeacher.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #47
<br/>
---
- 사진으로 대체 ^^,
<br/>
---
코드가 정신없어서 주의가 필요하지만 지금 리팩하다간 제 정신이 주의가 필요해서 이후에 리팩하겠습니다 눈물 주르륵

[feat] getTodayScheduleByTeacher

---

src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByTeacherResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleTimeAndCountInfo.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodaySchedule.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayScheduleDetailByTeacher.java
src/main/java/gwasuwonshot/tutice/schedule/entity/ScheduleStatus.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #61 
<br/>
---
- 오늘 이전 + 취소 뺴고 다 
- 오늘 + 미래 뺴고 + 취소 빼고 다
- -> 이렇게 구한 횟수에 +1을 더해 현재 보여주고자 하는 기대회차 반환
<br/>
---

[fix] getExpectedScheduleCount

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacher.java
src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacherResponseDto.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java

---
closes #87 
<br/>
---
- 유저가 선생님인지 역할확인
- 유저의 레슨중 종료여부 상관없이 가져와서 현재 퍼센트와 현재사이클의 스케쥴 가져오기
<br/>
---

[feat] get lesson by teacher

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetLatestScheduleByTeacherResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/LatestSchedule.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByTime.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #75 
<br/>
---
<br/>
---
scheduleResponse에서 공통으로 쓰이는 dto가 있는데 클래스명을 맨 처음 지은걸로 사용하고 있어서 추후 공통 클래스명으로 수정하겠습니다 (메모)

[feat] getLatestScheduleByTeacher

---

src/main/java/gwasuwonshot/tutice/common/resolver/WebConfig.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByTeacherResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodaySchedule.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #90
<br/>
---
- todaySchedule 객체 내에 있어서 해당 로직에서만 boolean값을 체크해 반환하도록 했숨니다 -!
<br/>
---

[fix] isMissingAttendanceByLesson 컬럼 추가

---

src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/lesson/exception/notfound/NotFoundLessonParentsException.java
src/main/java/gwasuwonshot/tutice/schedule/exception/InvalidScheduleException.java
src/main/java/gwasuwonshot/tutice/schedule/exception/NotFoundScheduleException.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
src/main/java/gwasuwonshot/tutice/user/controller/NotificationController.java
src/main/java/gwasuwonshot/tutice/user/dto/response/RequestAttendanceNotificationResponseDto.java
src/main/java/gwasuwonshot/tutice/user/exception/NotificationFailException.java
src/main/java/gwasuwonshot/tutice/user/exception/userException/NotAllowedNotificationException.java
src/main/java/gwasuwonshot/tutice/user/repository/NotificationLogRepository.java
src/main/java/gwasuwonshot/tutice/user/service/NotificationService.java

---
closes #89 
<br/>
---
- 유저가 존재하고 선생님인지 확인
- 들어온 스케쥴이 존재하는지, 스케쥴의 레슨이 유저와 연결되어있는지확인
- 레슨에 학부모가 연결되어있는지확인
- 학부모가 알림을 허용했는지 확인
- 제목과 텍스트를 구성해 알림보내기
- 보내진게 맞으면  알림 기록하기
<br/>
---
알림 텍스트 바디부분 컨스턴트 클래스로 리팩함 해야함

[feat]request attendance notification

---

src/main/java/gwasuwonshot/tutice/user/entity/NotificationConstant.java
src/main/java/gwasuwonshot/tutice/user/entity/NotificationLog.java

---
closes #
<br/>
---
- 
-
<br/>
---

feat: 🎸 알림 컨텐츠 상수 이넘으로 분리

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/user/controller/NotificationController.java
src/main/java/gwasuwonshot/tutice/user/dto/response/RequestPaymentRecordNotificationResponseDto.java
src/main/java/gwasuwonshot/tutice/user/entity/NotificationConstant.java
src/main/java/gwasuwonshot/tutice/user/service/NotificationService.java

---
closes #96 
<br/>
---
- 유저가 존재하고 선생님인지 확인
- 들어온 레슨이 존재하는지, 레슨이 유저와 연결되어있는지확인
- 레슨에 학부모가 연결되어있는지확인
- 학부모가 알림을 허용했는지 확인
- 제목과 텍스트를 구성해 알림보내기
- 보내진게 맞으면 알림 기록하기
<br/>
---
알림에 대한 제목-컨텐츠를 짝지어 이넘으로 만듬.
각 알림은 getter private 임으로, 각알림의 제목, 컨텐츠를 쓰고싶으면 메소드를 이용해야함

[feat] request payment record notification

---

src/main/java/gwasuwonshot/tutice/TuticeApplication.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
src/main/java/gwasuwonshot/tutice/user/entity/NotificationConstant.java

---
closes #93 
<br/>
---
- 1. 오늘 날짜 + endTime + 상태 없음 바탕으로 출결체크 알림
- 2. 오늘 날짜 + endTime 후 30분 뒤 + 상태 없음 바탕으로 출결체크 알림
<br/>
---

[feat] postMissingAttendance

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/RegularScheduleAssembler.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/dto/request/GetTemporaryScheduleRequestDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/request/RegularScheduleByDate.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTemporaryScheduleResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByDateAndTime.java
src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #103
<br/>
---
- 기존 캘린더 자동 생성 로직 이용
<br/>
---
기존 자동 생성 메서드랑 거의 유사해서 나중에 리팩하려고 TODO 남겨놨습니다 - !

getTemporarySchedule

---

src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java

---
closes #103
<br/>
---
- 바보같이 HTTP method를 .... 
<br/>
---

[fix] getTemporarySchedule

---

src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #108 
<br/>
---
- 
-
<br/>
---

[fix] 🐛 수업연장 여부 검사시 상태없음이 없음 -> 연장필요ㅗㄹ 변경

---

src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #
<br/>
---
- 
-
<br/>
---

최근스케쥴 뷰에서 isMissing연장 트리거변경

---

src/main/java/gwasuwonshot/tutice/lesson/service/PaymentRecordService.java

---
closes #112 
<br/>
---
- 
-
<br/>
---

[fix] getPaymentRecordByUser

---

src/main/java/gwasuwonshot/tutice/lesson/service/PaymentRecordService.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #
<br/>
---
- 
-
<br/>
---

fix : getPaymentRecordUser 선불후불로 입금내역가져오는 차이로 변경

---

src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTemporaryScheduleResponseDto.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TemporarySchedule.java
src/main/java/gwasuwonshot/tutice/schedule/dto/response/TemporaryScheduleByTime.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #111 
<br/>
---
클라 요청으로 날짜별로 스케줄 묶어서 반환으로 수정했습니다 - !
<br/>
---

[fix] getTemporarySchedule res 수정

---

src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByParentsResponseDto.java

---
closes #117
<br/>
---
- 
-
<br/>
---

[fix] 선생님 이름 res 수정

---

src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java

---
closes #119
<br/>
---
- 
-
<br/>
---

[hotfix] accesstoken 기간 연장

---

src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java

---
closes #121
<br/>
---
- accesstoken -> 2시간
- refreshtoken -> 2주
<br/>
---

[hotfix] setTokenPeriod

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
src/main/java/gwasuwonshot/tutice/user/dto/response/GetUserNameResponseDto.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
closes #124
<br/>
---
- Token 통해 유저이름 반환
<br/>
---
X

[feat] getUserName

---

src/main/java/gwasuwonshot/tutice/lesson/dto/response/CreateLessonResponseDto.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
closes #141
<br/>
---
- responsed에 lessonIdx 추가했습니다 - !
<br/>
---

[fix] createLesson response에 lessonIdx 추가

---

src/main/java/gwasuwonshot/tutice/lesson/dto/response/CreateLessonResponseDto.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #147
<br/>
---
-  현재날짜, 시간 구함
- 수업이 현재날짜보다 이전이면 -> 정보 반환
- 수업이 현재날짜일때 현재시간이 수업시작시간보다 이후이면(즉 현재 수업시작한상태면) -> 반환
-
<br/>
---

[fix] get lesosn schedule

---

src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/user/exception/authException/AlreadyExistEmailException.java
src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
closes #150
<br/>
---
- 이메일 중복 체크 추가
<br/>
---
추후 소셜로그인까지 추가되면 provider+email까지 같이 검증할 지 등 기획과 자세한 논의하면 좋을 것 같아요!

[fix] localLogin 이메일 중복 에러 추가

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
src/main/java/gwasuwonshot/tutice/user/dto/request/CheckDuplicationEmailRequestDto.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
closes #153 
<br/>
---
- 이슈 TODO와 동일
<br/>
---
추후, 프론트와 소셜로그인 담당 부분 논의 후 provider까지 고려하게 되면 수정하기!

[feat] checkDuplicationEmail

---

src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValid.java
src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValidator.java
src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonMaintenanceRequestDto.java
src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestRegularSchedule.java

---
closes #159 
<br/>
---
- 목적 : validator 단에서 시작시간<종료시간 검증
- 한일 : 커스텀 어노테이션을 만들어 `CreateLessonRequestRegularSchedule` Dto 객체에서 시작시간<종료시간 검증
<br/>
---

[fix] create lesson

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
closes #161 
<br/>
---
- NO_STATUS(상태없음)이면 false, 나머지는 true를 반환하도록 했습니다
<br/>
---

[feat] getAttendanceExistenceByTeacher 

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
closes #163
<br/>
---
- 유저 존재 여부 확인
- refreshToken 삭제
- accessToken 검증 후, 시간이 유효한 accessToken은 redis에 blackList로 저장
- 기획&웨비와 논의 후, AccessToken 기간을 2주로 임시 고정했습니다
<br/>
---

[feat] logout

---

src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailResponseDto.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
closes #166 
<br/>
---
- lessonService에 있는 createLessonCode를 lesson 도메인으로 이동
- lessonDetail responseDTO에 lessonCode 추가
<br/>
---

[feat] get lesson detail

---

src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java

---
#169
<br/>
---
- 
-
<br/>
---
추후 문제되는 부분 원인 찾아서 재해결하겠습니다 !

fix:🐛 로그아웃 오류 임시 해결

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonRegularSchedule/GetLessonRegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonRegularSchedule/GetLessonRegularScheduleResponseDto.java
src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java
src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
close #171
<br/>
---
- 유저가 존재하는지, 수업이 존재하는지, 유저와 수업이 연결되어있는지 확인후
- 먼저 시간대별로 정기일정을 그룹핑하고(RegularSchedule domain에 groupByDuplicateTimeRegularScheduleIndexList 함수로 분리)
- 그룹핑된 정기일정들을 
- 1차로 시간대별로 묶인 항목의 내부 요일리스트를 월 ~ 일 순으로 정렬
- 2차로 시간대별로 묶은 항목을 내부 요일리스트를 월 ~ 일 순으로 정렬
- 예시
"regularScheduleList" : [
{"dayOfWeek" : "목", "startTime" : "13:00:00" , "endTime" : "14:00:00"},
{"dayOfWeek" : "수", "startTime" : "13:00:00" , "endTime" : "15:00:00"},
{"dayOfWeek" : "월", "startTime" : "13:00:00" , "endTime" : "14:00:00"},
{"dayOfWeek" : "화", "startTime" : "14:30:00" , "endTime" : "15:50:00"},
{"dayOfWeek" : "토", "startTime" : "13:00:00" , "endTime" : "14:00:00"}
]
일때
정기일정 그룹핑 : [
{ [ 목 , 월 , 토 ] , "startTime" : "13:00:00" , "endTime" : "14:00:00"},
{ [ 수 ] , "startTime" : "13:00:00" , "endTime" : …

[feat] get lesson regular schedule

---

src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacher.java
src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacherLatestRegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
close #168 
<br/>
---
- dto에 regularSchedule 만들기
- regularschedule entity에 주어진 날짜(인자로받음)에서 가장 가까운 다가오는 요일을 구하는 메소드 추가
- 서비스 로직에 삭제된 (deleted_at이 null이 아닌) 수업을 거르는 로직 추가
<br/>
---

[fix] get lesson by teacher

---

src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacher.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
close #176 
<br/>
---
- response dto에 isFinished 필드추가
- 서비스레이어에서도 isFinished 필드 채우게 수정
<br/>
---

[fix] getLessonByTeacher

---

src/main/java/gwasuwonshot/tutice/user/dto/request/UpdateUserDeviceTokenRequest.java

---
close #193
<br/>
---
- deviceToken nullable 허용
<br/>
---

[feat] deviceToken nullable 허용

---

src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
close #196
<br/>
---
- getScheduleByUser startTime 기준 오름차순 변경
<br/>
---

[fix] getScheduleByUser startTime 기준 오름차순 변경

---

src/main/java/gwasuwonshot/tutice/common/advice/ControllerExceptionAdvice.java
src/main/java/gwasuwonshot/tutice/common/controller/CommonController.java
src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/Enum.java
src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValid.java
src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValidator.java

---
close #198 
<br/>
---
- createLessonValid 어노테이션 벨리데이터의 검사로직을 오버로딩하여 common controller에 사용
- 어노테이션 벨리데이터에서의 에러메시지를 ErrorStatus로 한번에 모아 ErrorStatus를 통해 에러처리한곳을 찾아갈수있게함
<br/>
---

[feat] validate time range

---

README.md
src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestAccount.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Payment.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/user/dto/response/GetAccountByLessonResponse.java
src/main/java/gwasuwonshot/tutice/user/entity/Account.java
src/main/java/gwasuwonshot/tutice/user/entity/Bank.java

---
close #
<br/>
---
- 
-
<br/>
---

readme update

---

src/main/java/gwasuwonshot/tutice/user/entity/Provider.java
src/main/java/gwasuwonshot/tutice/user/entity/User.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
close #205
<br/>
---
- 논의한 ERD 구조에 따라 변경 및 추가
<br/>
---

[feat] modifyERD

---

src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
src/main/java/gwasuwonshot/tutice/user/exception/userException/ForbiddenNotificationUserException.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
close #211 
<br/>
---
- DB의 deviceToken 값 유무 및 비어있는 경우에 따라 상태코드로 반영
(200 - 허용, 403- 비허용)
<br/>
---

[feat] getNotificationStatus

---

build.gradle
src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/config/sms/SmsService.java
src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
src/main/java/gwasuwonshot/tutice/user/dto/request/SendValidationNumberRequest.java
src/main/java/gwasuwonshot/tutice/user/exception/authException/AlreadyExistPhoneNumberException.java
src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
close #209 
<br/>
---
- 올바른 전화번호 형식 확인 (하이픈 제외)
- 이미 가입된 전화번호인지 확인
- 랜덤 6자리 인증번호 생성 후, 전화번호로 전송
- redis에 인증번호 저장(기획과 논의 후, 5분으로 시간 확정) -> 추후 검증 로직에서 활용 예정
<br/>
---- 
- sms 기능 관련해서 build.gradle 파일 업데이트 필요합니다!
- application.yaml 파일도 업데이트 되어서 notion에 명세해뒀습니도-

[feat] sendValidationNumber

---

build.gradle
src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/config/sms/SmsService.java
src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
src/main/java/gwasuwonshot/tutice/user/dto/request/SendValidationNumberRequest.java
src/main/java/gwasuwonshot/tutice/user/dto/request/ValidatePhoneRequest.java
src/main/java/gwasuwonshot/tutice/user/exception/authException/AlreadyExistPhoneNumberException.java
src/main/java/gwasuwonshot/tutice/user/exception/authException/InvalidValidationNumberException.java
src/main/java/gwasuwonshot/tutice/user/exception/authException/NotFoundValidationNumberException.java
src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
close #210
<br/>
---
- 인증 시간 (5분) 초과 확인
실패(404)
- 인증 번호 일치 여부 확인
실패(401)
성공(200) -> redis에서 삭제
<br/>
---
redis EC2에서 실행했더니 용량 문제로 대체 방법 고민중입니다 !

[feat] validatePhone

---

src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
src/main/java/gwasuwonshot/tutice/user/dto/request/ReissueTokenRequest.java
src/main/java/gwasuwonshot/tutice/user/dto/response/ReissueTokenResponse.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
close #208 
<br/>
---
- accessToken 만료되었는지 여부 확인
- accessToken 기반 userIdx 바탕으로 유저 검증 확인
- refreshToken 만료 및 일치 여부 확인
- acessToken 및 refreshToken 재발급
<br/>
---
accessToken 개발 기간 동안 임의로 늘려둔 것 추후 수정 필요합니다 !
(개발 검증할 때는 로컬에서 수정하여 확인했어용)

[feat] reissueToken

---

src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java

---
close #215 
<br/>
---
- login -> loginAndTempSignUp 함수명 변경! (혼란 방지)
<br/>
---

[fix] loginAndTempSignUp

---

src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestLesson.java
src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
src/main/java/gwasuwonshot/tutice/user/entity/User.java
src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java

---
close #220 
<br/>
---
- createLesson에서 parenstsPhone
- 존재 X : 기존로직 동일
- 존재 O
- 해당 번호가 기존 회원 : lesson에 연결
- 해당 번호가 기존회원이 아님 : TEMP_PARENTS 로 임시 학부모 유저 생성해 lesson에 연결
<br/>
---

[fix] createLesson

---

src/main/java/gwasuwonshot/tutice/user/entity/User.java
src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
close #221
<br/>
---
- provider TEMP인 경우 (학부모 연락처 유저가 있는 경우)
--> socialToken 및 proivder 업데이트
--> 회원가입에 필요한 정보 업데이트
<br/>
---

[fix] signUp

---

src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
close #223 
<br/>
---
- 취소회차이면 반복문에서 다음으로 넘어가도록함
<br/>
---

[fix]getScheduleByLesson

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
close #226 
<br/>
---
- scheduleRepository 메소드 수정
- getScheduleByLesosn, getCanceledScheduleByLesson 서비스 로직 메소드 변경
<br/>
---

[feat] get canceled schedule by lesson

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java

---
close #228
<br/>
---
- 스케줄 삭제 -> 정기일정 따라 새로운 스케줄 생성
<br/>
---
우선 출결상태가 존재하면 삭제가 불가능하도록 했는데, 해당 부분 허용할지 재논의하면 좋을 것 같아요 !

[feat] deleteSchedule

---

src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
src/main/java/gwasuwonshot/tutice/external/naver/NaverService.java
src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
src/main/java/gwasuwonshot/tutice/user/dto/request/GetNaverProfileInfoRequest.java
src/main/java/gwasuwonshot/tutice/user/dto/response/GetNaverProfileInfoResponse.java

---
close #230
<br/>
---
- 네이버로부터 인증토큰 받아서 그대로 사용자 정보 반환하도록 했습니다 !
<br/>
---

[feat] getNaverProfileInfo

---

src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestAccount.java
src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
close #232 
<br/>
---
- request dto에서 account.name 삭제
- 내부적으로 선생님이름으로 계좌이름을  저장
<br/>
---

[fix]createLesson

---

src/main/java/gwasuwonshot/tutice/schedule/entity/ScheduleStatus.java

---
close #237 
<br/>
---
- 
-
<br/>
---

[fix] ScheduleStatus

---

src/main/java/gwasuwonshot/tutice/user/service/UserService.java

---
close #242
<br/>
---
- 
-
<br/>
---

[fix] sendValidationNumber

---

src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java

---
close #244
<br/>
---
- 번호로 유저 찾았을 때, 없는 경우 먼저 유저를 생성하도록 수정했습니다!
- 추가 변경 사항 있으면 수정 부탁드려요
<br/>
---

[fix] updateLessonParents
